EEG = pop_loadset('C:\Users\User\Desktop\NYCU\11102\BCI\HW2\Hw2_dataset-20230330T095307Z-001\Hw2_dataset\no_all.set');
FCz_data = EEG.data(strcmp({EEG.chanlocs.labels}, 'FCz'),:,:);
time_points = EEG.times;
event_types = {EEG.event.type};
correct_indices = find(contains(lower(event_types), 'correct'));
error_indices = find(contains(lower(event_types), 'wrong'));
correct_erp = squeeze(mean(FCz_data(:,:,correct_indices), 3));
error_erp = squeeze(mean(FCz_data(:,:,error_indices), 3));
figure;
plot(time_points, correct_erp, 'b', 'LineWidth', 1);
hold on;
plot(time_points, error_erp, 'r', 'LineWidth', 1);
xlabel('Time (ms)');
ylabel('Amplitude (uV)');
legend('Correct Feedback', 'Error Feedback');
title('ERP Without any operation');

EEG = pop_loadset('C:\Users\User\Desktop\NYCU\11102\BCI\HW2\Hw2_dataset-20230330T095307Z-001\Hw2_dataset\no_wrong.set');
FCz_data = EEG.data(strcmp({EEG.chanlocs.labels}, 'FCz'),:,:);
time_points = EEG.times;
event_types = {EEG.event.type};
error_indices = find(contains(lower(event_types), 'wrong'));
error_erp = squeeze(mean(FCz_data(:,:,error_indices), 3));
figure;
plot(time_points, error_erp, 'r', 'LineWidth', 1);
xlabel('Time (ms)');
ylabel('Amplitude (uV)');
legend('Error Feedback');
title('SNR(error feedback only) Without any operation');

EEG = pop_loadset('C:\Users\User\Desktop\NYCU\11102\BCI\HW2\Hw2_dataset-20230330T095307Z-001\Hw2_dataset\filter_all.set');
FCz_data = EEG.data(strcmp({EEG.chanlocs.labels}, 'FCz'),:,:);
time_points = EEG.times;
event_types = {EEG.event.type};
correct_indices = find(contains(lower(event_types), 'correct'));
error_indices = find(contains(lower(event_types), 'wrong'));
correct_erp = squeeze(mean(FCz_data(:,:,correct_indices), 3));
error_erp = squeeze(mean(FCz_data(:,:,error_indices), 3));
figure;
plot(time_points, correct_erp, 'b', 'LineWidth', 1);
hold on;
plot(time_points, error_erp, 'r', 'LineWidth', 1);
xlabel('Time (ms)');
ylabel('Amplitude (uV)');
legend('Correct Feedback', 'Error Feedback');
title('ERP Bandpass the signal');

EEG = pop_loadset('C:\Users\User\Desktop\NYCU\11102\BCI\HW2\Hw2_dataset-20230330T095307Z-001\Hw2_dataset\filter_all.set');
FCz_data = EEG.data(strcmp({EEG.chanlocs.labels}, 'FCz'),:,:);
time_points = EEG.times;
event_types = {EEG.event.type};
error_indices = find(contains(lower(event_types), 'wrong'));
error_erp = squeeze(mean(FCz_data(:,:,error_indices), 3));
figure;
plot(time_points, error_erp, 'r', 'LineWidth', 1);
xlabel('Time (ms)');
ylabel('Amplitude (uV)');
legend('Error Feedback');
title('SNR(error feedback only) Bandpass the signal');

EEG = pop_loadset('C:\Users\User\Desktop\NYCU\11102\BCI\HW2\Hw2_dataset-20230330T095307Z-001\Hw2_dataset\ICAremove.set');
FCz_data = EEG.data(strcmp({EEG.chanlocs.labels}, 'FCz'),:,:);
time_points = EEG.times;
event_types = {EEG.event.type};
correct_indices = find(contains(lower(event_types), 'correct'));
error_indices = find(contains(lower(event_types), 'wrong'));
correct_erp = squeeze(mean(FCz_data(:,:,correct_indices), 3));
error_erp = squeeze(mean(FCz_data(:,:,error_indices), 3));
figure;
plot(time_points, correct_erp, 'b', 'LineWidth', 1);
hold on;
plot(time_points, error_erp, 'r', 'LineWidth', 1);
xlabel('Time (ms)');
ylabel('Amplitude (uV)');
legend('Correct Feedback', 'Error Feedback');
title('ERP Run ICA');

EEG = pop_loadset('C:\Users\User\Desktop\NYCU\11102\BCI\HW2\Hw2_dataset-20230330T095307Z-001\Hw2_dataset\ICAremove.set');
FCz_data = EEG.data(strcmp({EEG.chanlocs.labels}, 'FCz'),:,:);
time_points = EEG.times;
event_types = {EEG.event.type};
error_indices = find(contains(lower(event_types), 'wrong'));
error_erp = squeeze(mean(FCz_data(:,:,error_indices), 3));
figure;
plot(time_points, error_erp, 'r', 'LineWidth', 1);
xlabel('Time (ms)');
ylabel('Amplitude (uV)');
legend('Error Feedback');
title('SNR(error feedback only) Run ICA');

EEG = pop_loadset('C:\Users\User\Desktop\NYCU\11102\BCI\HW2\Hw2_dataset-20230330T095307Z-001\Hw2_dataset\filterAndICAremove_all.set');
FCz_data = EEG.data(strcmp({EEG.chanlocs.labels}, 'FCz'),:,:);
time_points = EEG.times;
event_types = {EEG.event.type};
correct_indices = find(contains(lower(event_types), 'correct'));
error_indices = find(contains(lower(event_types), 'wrong'));
correct_erp = squeeze(mean(FCz_data(:,:,correct_indices), 3));
error_erp = squeeze(mean(FCz_data(:,:,error_indices), 3));
figure;
plot(time_points, correct_erp, 'b', 'LineWidth', 1);
hold on;
plot(time_points, error_erp, 'r', 'LineWidth', 1);
xlabel('Time (ms)');
ylabel('Amplitude (uV)');
legend('Correct Feedback', 'Error Feedback');
title('ERP Bandpass the signal and run ICA');

EEG = pop_loadset('C:\Users\User\Desktop\NYCU\11102\BCI\HW2\Hw2_dataset-20230330T095307Z-001\Hw2_dataset\filterAndICAremove_all.set');
FCz_data = EEG.data(strcmp({EEG.chanlocs.labels}, 'FCz'),:,:);
time_points = EEG.times;
event_types = {EEG.event.type};
error_indices = find(contains(lower(event_types), 'wrong'));
error_erp = squeeze(mean(FCz_data(:,:,error_indices), 3));
figure;
plot(time_points, error_erp, 'r', 'LineWidth', 1);
xlabel('Time (ms)');
ylabel('Amplitude (uV)');
legend('Error Feedback');
title('SNR(error feedback only) Bandpass the signal and run ICA');